### PR TITLE
adding inline comments and md cell

### PR DESCRIPTION
**Pull request by ggrrll**
Hi @jaidevd ,

with reference to #55   I added  some comments and changed some plots in the notebook -- it seems correct, but I would double check with some other implementations (matlab?), before publishing it

### CODE REVIEW

**Comment by jaidevd** [comment]
Thanks for this, @ggrrll. Can you please give me write access to your fork so that I can fix the failing test?

**Comment by ggrrll** [comment]
sure -- done

**Comment by ggrrll** [comment]
Thanks for the merge.


(trivial question, as I am not a git expert) 

Since you deleted the branch on my fork, I tried few commands that didn't work to sync the local repo to the remote origin (like `git fetch -p` and `git remote prune origin`). 

Then I tried to delete it directly and I  got this :
screen shot 2018-09-05 at 12 32 10

Is it ok you think to run it with `-D` ? thanks

**Comment by jaidevd** [comment]
Can you pull that branch from jaidevd/pyhht into your branch and try -d again? I wouldn't recommend -D

**Comment by ggrrll** [comment]
yeah ... this helped indeed https://help.github.com/articles/syncing-a-fork/

**Pull request merged**
